// Automatically generated from public/gallery

export const galleryImages: string[] = [
  "/gallery/Amber & Kendall Wedding/Amber&Kendall.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&Kendall10.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&Kendall2.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&Kendall3.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&Kendall4.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&Kendall5.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&Kendall6.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&Kendall7.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&Kendall8.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&Kendall9.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallAmbience2.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallAmbience4.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallAmbienceShot.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallAmience11.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallDining.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallFlowerShot.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallFlowerShot2.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallFlowers.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallMenu.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallMoreTables.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallOutdoor.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallTableShot.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallTableShot3.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallTabless.jpeg",
  "/gallery/Amber & Kendall Wedding/Amber&KendallVenueShot.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan10.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan11.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan12.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan13.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan14.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan15.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan16.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan17.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan18.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan19.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan7.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan8.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&Jordan9.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&JordanChurchShot.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&JordanCoupleShot1.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&JordanDrapes.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&JordanKissingShot.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&JordanStageShot.jpeg",
  "/gallery/Jenny & Jordan Wedding/Jenny&JordanTablesOverheadShot.jpeg",
  "/gallery/LVD Floral Images/LVDFloralBride.jpeg",
  "/gallery/LVD Floral Images/LVDFloralBride2.jpeg",
  "/gallery/LVD Floral Images/LVDFloralCouple.jpeg",
  "/gallery/LVD Floral Images/LVDFloralCoupleStage.jpeg"
];
